### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by MC-E** [Lotayou/Face-Renovation#30]
Hi, the released Pre-trained model seems to be hardly related to your paper. Furthermore, I trained the model with default training settings, but I can not get the same performance as shown in your paper. Looking forward to hearing from you.Thank you.

**Comment by vvictoryuki** [comment]
I encountered the same problem, in detail, I have following questions:
(1) the provided pretrained model is implemented with **lipspadeGenerator** which seems to be quite different from the model mentioned in the paper. Actually, before you provided the pretrained model, I take the **HiFaceGANGenerator** for granted, because this model is closer to the description in the paper. The biggest problem with the **lipspadeGenerator** model is that the input of the SPADE module is the degraded image instead of the feature output by the previous Suppression module.
(2) the provided pretrained model seems to be wrong. Even if I get degraded images from degrade.py, the output of x16, face_renov, face_renov_2, x4sr(the provided pretrained model of x4sr seems to be implemented with the **spadeGenerator** derectly instead of the **lipspadeGenerator**) is bad.
(3) My test results cannot be up to the performance of the Table1 in your paper of HiFaceGAN. Can you check the config file and confirm if there is any problem or can you provide me with some suggestions so that I can reproduced your results
